services:
  app:
    image: myapp
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www
      - ./storage/Firebase/gestion-scolaire-75b42-firebase-adminsdk-t4mkq-71dad755d5.json:/var/www/storage/Firebase/gestion-scolaire-75b42-firebase-adminsdk-t4mkq-71dad755d5.json
    networks:
      - laravel
    env_file: 
      - .env

  webserver:
    image: nginx:alpine
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9321:80"
    depends_on:
      - app
      - db
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: re@louZ01
      MYSQL_DATABASE: Projet_Scolaire
      MYSQL_USER: diedhiouousseynou53
      MYSQL_PASSWORD: re@louZ01
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
