version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Gestion-App-Laravel
    volumes:
      - .:/var/www
      - ./gestion-ecole-laravel-firebase.json:/home/dev/Documents/gestion_scolaire_V2_Last/storage/firebase/firebase_reencoded.key
    networks:
      - app-network
    depends_on:
      - db

  webserver:
    image: nginx:latest
    container_name: Gestion-App-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.dz
      - .:/var/www
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:14.13
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: lastdayoflaravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
 
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge