version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Gestion-App-Laravel
    volumes:
      - .:/var/www/html
      - ./gestion-pedagogique-laravel.json:/home/ndiaga-lo/Musique/last-day-of-laravel/storage/Firebase/firebase_encoded.key
    networks:
      - app-network
    expose:
      - "9000" # Expose PHP-FPM pour que Nginx puisse s'y connecter
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  webserver:
    image: nginx:latest
    container_name: Gestion-App-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: postgres:14.13
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: lastdayoflaravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
